/*
 * This source file was generated by the Gradle 'init' task
 */
package com.wharvex.nclos.app;

import static com.wharvex.nclos.app.MessageUtils.getMessage;
import static com.wharvex.nclos.utilities.StringUtils.join;
import static com.wharvex.nclos.utilities.StringUtils.split;

import org.apache.commons.text.WordUtils;

import com.wharvex.nclos.list.LinkedList;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
